# Generated by Django 3.1.2 on 2021-04-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210414_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rut',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
