# Generated by Django 3.1.2 on 2021-04-26 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210417_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='saildetail',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.ticket'),
            preserve_default=False,
        ),
    ]
