# Generated by Django 3.1.2 on 2021-05-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_saildetail_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='token',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
