# Generated by Django 3.1.2 on 2021-05-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ticket_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
